#!/bin/bash
set -e

sudo pacman -Syu --noconfirm - < pkglist

sudo mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
sudo systemctl enable --now mariadb.service

sudo usermod -a -G input ash

mkdir -p ~/scripts ~/recordings

cp -a config/. /home/ash/.config/
cp -a scripts/. /home/ash/scripts/
cp -R wallpapers/ /home/ash/wallpapers

sudo chmod +x /home/ash/scripts/*

sudo mkdir /mnt/storage

echo "\n/dev/disk/by-uuid/eab3b3c5-7473-4308-bf3a-633def59c06c /mnt/storage auto nosuid,nodev,nofail,x-gvfs-show 0 0" | sudo tee -a /etc/fstab
systemctl daemon-reload
sudo mount -a

git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
yay -Syu jetbrains-toolbox plex-media-server aria2 docker-desktop --noconfirm
