#!/bin/bash

get_title() {
    input="$1"
    echo " $1" | sed -E 's/_/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1'
}

current_title=""

while true; do
    win_id=$(xprop -root _NET_ACTIVE_WINDOW | awk -F ' ' '{print $NF}')

    if [ -n "$win_id" ] && [ "$win_id" != "0x0" ]; then
        class=$(xprop -id "$win_id" WM_CLASS 2>/dev/null | awk -F '"' '{print $4}')
        if [ -n "$class" ]; then
            clean_class=$(echo "$class" | cut -d '-' -f 1 | sed 's/ *$//')
            get_title "$clean_class"
        else
            echo "Unknown class"
        fi
    else
        echo "No window focused"
    fi


    sleep 0.1
done